# Generated by Django 4.0.6 on 2022-07-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legistations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislationpage',
            name='date_into_practice',
            field=models.DateField(default='07-07-2022'),
        ),
    ]
