# Generated by Django 4.0.6 on 2022-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legistations', '0003_alter_legislationpage_date_into_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislationpage',
            name='date_issued',
            field=models.DateField(default='2022-07-07'),
        ),
    ]
