# Generated by Django 4.0.6 on 2022-07-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legistations', '0004_alter_legislationpage_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislationpage',
            name='date_into_practice',
            field=models.DateField(default='07-07-2022'),
        ),
        migrations.AlterField(
            model_name='legislationpage',
            name='date_issued',
            field=models.DateField(default='07-07-2022'),
        ),
    ]
