# Generated by Django 4.0.6 on 2022-07-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legistations', '0005_alter_legislationpage_date_into_practice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislationpage',
            name='date_into_practice',
        ),
    ]
