# Generated by Django 4.0.6 on 2022-07-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legistations', '0006_remove_legislationpage_date_into_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislationpage',
            name='date_issued',
        ),
    ]
